import CodeBlock from "./PageGetStarted/CodeBlock";
import { REPO_URL } from "./NavBar";

const install = `git clone https://github.com/vic663/nu_agent && cd nu_agent
python -m venv .venv && source .venv/bin/activate
pip install -e ".[dev]"            # add ,anthropic or ,openai for LLM planning

nuagent doctor                      # what solvers / executors / LLM keys are available?
pytest -q                           # unit tests: no solver needed (OpenFOAM/FESTIM tests auto-skip)`;

const steps = [
  {
    title: "Deterministic V&V workflow on the mock solver",
    caption: "About five seconds, no OpenFOAM needed. The report lands in runs/<name>/report.md.",
    code: `nuagent run examples/heated_pipe/laminar_verification.yaml --backend mock`,
  },
  {
    title: "The same workflow on real OpenFOAM",
    caption: "About 30 seconds including the three-level grid study.",
    code: `nuagent run examples/heated_pipe/laminar_verification.yaml          # needs OpenFOAM on PATH ...
docker compose -f docker/compose.yaml run openfoam \\
    nuagent run examples/heated_pipe/laminar_verification.yaml     # ... or use the container`,
  },
  {
    title: "Tritium permeation with FESTIM in its container",
    caption: "FESTIM 2.x on dolfinx; the case is generated and post-processed by NuAgent.",
    code: `docker compose -f docker/compose.yaml run festim \\
    nuagent run examples/tritium_permeation/permeation_verification.yaml`,
  },
  {
    title: "Bayesian calibration and Sobol UQ of TDS trap parameters",
    caption: "Reduced-order model, no solver. Qualification of this block is still pending (see About).",
    code: `nuagent run examples/tds_calibration/tds_reduced_calibration.yaml`,
  },
  {
    title: "Natural-language planning with an LLM",
    caption: "The plan is validated against the typed schema, then the deterministic pipeline runs.",
    code: `export ANTHROPIC_API_KEY=...   # or OPENAI_API_KEY / OPENAI_BASE_URL for a local vLLM/Ollama server
nuagent ask "Turbulent water flow in a 20 mm pipe at Re=20000 with 50 kW/m2 heating; validate Nu and f" --plan-only`,
  },
  {
    title: "Qualify the agent",
    caption: "Success rate, retries, validation and GCI outcomes over the task suite; --repeats adds pass^k.",
    code: `nuagent eval evals/tasks --backend mock --policy rules --repeats 3`,
  },
];

const llmOptions = [
  ["No LLM (default)", "--policy rules", "deterministic, reproducible; what CI and the evals use"],
  ["Hosted, Anthropic", 'pip install -e ".[anthropic]", ANTHROPIC_API_KEY, NUAGENT_LLM_MODEL=anthropic:claude-sonnet-4-5', "structured output via tool calling"],
  ["Hosted, OpenAI", 'pip install -e ".[openai]", OPENAI_API_KEY, NUAGENT_LLM_MODEL=openai:gpt-4o', ""],
  ["Local, Ollama", 'pip install -e ".[openai]", ollama pull qwen2.5:14b, OPENAI_BASE_URL=http://localhost:11434/v1, NUAGENT_LLM_MODEL=openai:qwen2.5:14b', "any model that supports tool calling; 7 to 14B quantised models run on a laptop"],
  ["Local, vLLM (cluster)", "same as above with the vLLM server's OPENAI_BASE_URL", "70B-class open-weights models"],
  ["Local via langchain-ollama", 'pip install -e ".[ollama]", NUAGENT_LLM_MODEL=ollama:qwen2.5:14b', "alternative to the OpenAI-compatible route"],
];

const docs = [
  ["Hands-on guide", "docs/tutorial.md", "install, first run, how to read a report, writing your own spec, OpenFOAM / FESTIM / LLM / SLURM set-up, troubleshooting"],
  ["Design and architecture", "docs/design.md", "state machine, guardrails, qualification strategy"],
  ["Case catalogue", "docs/case_catalogue.md", "benchmark and application cases (fission, fusion, aerospace)"],
  ["Agent architecture review", "docs/agent_architecture_review.md", "why NuAgent is a workflow with a verifier rather than a multi-agent chat"],
  ["Aerospace needs review", "docs/aerospace_review.md", "CFD Vision 2030, AIAA G-077, ASME V&V 20, NASA-STD-7009, certification by analysis"],
  ["Roadmap", "docs/roadmap.md", "coupled CFD to tritium permeation, MHD duct, HPC, MCP server"],
  ["Example reports", "docs/examples", "generated by the workflow from real OpenFOAM runs"],
];

const PageGetStarted = () => {
  return (
    <div className="space-y-10 p-6 max-w-6xl mx-auto font-lato">
      <div>
        <h1 className="text-4xl font-bold text-brand-700 mb-2 font-serif_title">Get Started</h1>
        <p className="text-stone-600">
          Python 3.10 or newer. The mock solver runs anywhere; OpenFOAM and FESTIM need Linux, WSL2 or
          the provided Docker containers. Every command below is the quick start from the repository README.
        </p>
      </div>

      <section className="space-y-3">
        <h2 className="text-2xl font-semibold text-brand-700 font-serif_title">Install</h2>
        <CodeBlock code={install} />
      </section>

      <section className="space-y-6">
        <h2 className="text-2xl font-semibold text-brand-700 font-serif_title">Six things to run</h2>
        {steps.map((s, i) => (
          <div key={s.title} className="border border-stone-200 rounded-lg shadow-md bg-white p-4 space-y-2">
            <h3 className="text-lg font-semibold text-stone-800">
              <span className="inline-flex items-center justify-center w-7 h-7 rounded-full bg-brand-700 text-white text-sm mr-3">
                {i + 1}
              </span>
              {s.title}
            </h3>
            <p className="text-sm text-stone-600">{s.caption}</p>
            <CodeBlock code={s.code} />
          </div>
        ))}
      </section>

      <section className="space-y-3">
        <h2 className="text-2xl font-semibold text-brand-700 font-serif_title">LLM options and cost</h2>
        <p className="text-stone-600 text-sm">
          The language model is optional and enters at exactly four bounded judgement points (plan, review,
          diagnose, critique), each a single structured-output call of roughly 5 to 15k tokens. A full
          LLM-assisted run costs cents with a hosted model and nothing with a local one.
        </p>
        <div className="overflow-x-auto">
          <table className="w-full text-sm border border-stone-200 rounded-lg overflow-hidden">
            <thead className="bg-brand-50 text-brand-800">
              <tr>
                <th className="text-left p-3">Option</th>
                <th className="text-left p-3">Setting</th>
                <th className="text-left p-3">Notes</th>
              </tr>
            </thead>
            <tbody>
              {llmOptions.map(([opt, setting, notes]) => (
                <tr key={opt} className="border-t border-stone-200 align-top">
                  <td className="p-3 font-semibold text-stone-800 whitespace-nowrap">{opt}</td>
                  <td className="p-3 font-mono text-xs text-stone-700">{setting}</td>
                  <td className="p-3 text-stone-600">{notes}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="space-y-3">
        <h2 className="text-2xl font-semibold text-brand-700 font-serif_title">Documentation</h2>
        <ul className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {docs.map(([title, path, blurb]) => (
            <li key={path} className="border border-stone-200 rounded-lg p-4 bg-white shadow-sm">
              <a
                href={`${REPO_URL}/blob/main/${path}`}
                target="_blank"
                rel="noopener noreferrer"
                className="font-semibold text-brand-700 hover:text-brand-500"
              >
                {title}
              </a>
              <p className="text-sm text-stone-600 mt-1">{blurb}</p>
            </li>
          ))}
        </ul>
      </section>
    </div>
  );
};

export default PageGetStarted;
