"""Mock backend: an analytical "solver" for CI, evals and agent development.

It produces results with *controlled* discretisation error so that the
verification machinery (Richardson extrapolation, GCI) has something real to
work on, and it can be made to mis-behave on purpose so that the
diagnose-and-retry loop is exercised deterministically:

* ``relax_U > 0.8`` on a turbulent case  -> the "run" diverges (NaN residuals)
* ``max_iterations < 500``                -> the run completes without converging

The run itself is a subprocess (``python -m nuagent.backends.mock.simulate``)
so that executors are exercised exactly as with a real solver.
"""

from __future__ import annotations

import json
import math
import shutil
import sys
from pathlib import Path
from typing import Any

from nuagent import __version__
from nuagent.backends.base import (
    CaseHandle,
    ConvergenceReport,
    QoIResult,
    spec_hash,
    write_case_metadata,
)
from nuagent.backends.openfoam.backend import ADJUSTABLE_NUMERICS, OpenFOAMBackend
from nuagent.backends.openfoam.logparse import parse_log_file
from nuagent.backends.openfoam.mesh import size_pipe_mesh, size_ribbed_mesh
from nuagent.spec import HeatedPipeCase, PermeationCase, RibbedTubeCase, SimulationSpec, TDSCase

ALLRUN = """#!/bin/bash
# Generated by NuAgent {version} — mock case '{name}'
cd "$(dirname "$0")" || exit 1
"{python}" -m nuagent.backends.mock.simulate . > log.mock 2>&1
rc=$?
echo "[nuagent] done (rc=$rc)"
exit $rc
"""


class MockBackend:
    name = "mock"

    def __init__(self, python: str | None = None) -> None:
        self.python = python or sys.executable
        self._of = OpenFOAMBackend()

    def available(self) -> bool:
        return True

    def build(
        self,
        spec: SimulationSpec,
        workdir: Path,
        refinement: float = 1.0,
        adjustments: dict[str, Any] | None = None,
    ) -> CaseHandle:
        workdir = Path(workdir)
        if workdir.exists():
            shutil.rmtree(workdir)
        workdir.mkdir(parents=True)
        case = spec.case
        meta: dict[str, Any] = {"adjustments": adjustments or {}, "log": "log.mock"}
        if isinstance(case, HeatedPipeCase):
            numerics = self._of.apply_adjustments(case.numerics, adjustments)
            mesh = (
                size_ribbed_mesh(case, refinement)
                if isinstance(case, RibbedTubeCase)
                else size_pipe_mesh(case, refinement)
            )
            h, n_cells = mesh.representative_h, mesh.n_cells
            meta.update({"numerics": numerics.model_dump(), "mesh": mesh.to_dict()})
        else:
            for key in adjustments or {}:
                if key not in ("n_steps", "atol", "rtol") and key not in ADJUSTABLE_NUMERICS:
                    raise ValueError(f"adjustment {key!r} not allowed")
            n_cells = int(round(case.n_cells * refinement))
            h = case.thickness / n_cells
            meta["params"] = {"n_cells": n_cells, "refinement": refinement}
        (workdir / "params.json").write_text(
            json.dumps(
                {
                    "spec": spec.model_dump(mode="json"),
                    "refinement": refinement,
                    "h": h,
                    "meta": meta,
                },
                indent=2,
            )
        )
        allrun = workdir / "Allrun"
        allrun.write_text(ALLRUN.format(version=__version__, name=spec.name, python=self.python))
        allrun.chmod(0o755)
        handle = CaseHandle(
            path=workdir,
            backend=self.name,
            spec_hash=spec_hash(spec, {"refinement": refinement, "adjustments": adjustments or {}}),
            refinement=refinement,
            representative_h=h,
            n_cells=n_cells,
            metadata=meta,
        )
        write_case_metadata(handle, spec)
        return handle

    def parse_log(self, case: CaseHandle) -> ConvergenceReport:
        target = case.metadata.get("numerics", {}).get("residual_target")
        return parse_log_file(case.path / "log.mock", residual_target=target)

    def extract_qois(self, case: CaseHandle, spec: SimulationSpec) -> QoIResult:
        path = case.path / "results.json"
        if not path.exists():
            raise FileNotFoundError(f"{path} missing — did the run complete?")
        d = json.loads(path.read_text())
        return QoIResult(
            values=d["values"],
            profiles=d.get("profiles", {}),
            checks=d.get("checks", {}),
            notes=d.get("notes", []),
        )


def _mock_values(spec: SimulationSpec, h: float, meta: dict) -> dict[str, Any]:
    """Deterministic synthetic results with second-order discretisation error."""
    from nuagent.physics import analytical, correlations, reduced

    case = spec.case
    if isinstance(case, HeatedPipeCase):
        h0 = 1.0e-3
        nu_ref = correlations.nusselt(case.reynolds, case.fluid.pr).value
        f_ref = correlations.friction_factor(case.reynolds).value
        extra = {}
        if isinstance(case, RibbedTubeCase):
            webb = correlations.webb_ribbed_tube(
                case.reynolds,
                case.fluid.pr,
                case.rib_height_over_diameter,
                case.rib_pitch_over_height,
            )
            nu0, f0 = nu_ref, f_ref
            nu_ref, f_ref = webb.nusselt, webb.friction_darcy
            extra = {
                "Nu_over_Nu0": nu_ref / nu0,
                "f_over_f0": f_ref / f0,
                "thermal_performance": correlations.thermal_performance_factor(
                    nu_ref / nu0, f_ref / f0
                ),
            }
        err = 0.01 * (h / h0) ** 2
        return {
            "values": {
                "Nu": nu_ref * (1.0 + err),
                "f": f_ref * (1.0 + 0.5 * err),
                "Re": case.reynolds,
                "Pr": case.fluid.pr,
                "n_cells": meta["mesh"]["n_cells"],
                **extra,
            },
            "checks": {"energy_balance_error": 1e-3 * (h / h0), "mass_balance_error": -1e-3},
            "profiles": {},
            "notes": ["synthetic result from the mock backend"],
        }
    if isinstance(case, PermeationCase):
        D = analytical.arrhenius(case.material.D_0, case.material.E_D, case.temperature)
        L = case.thickness
        err = 0.05 * (h / (L / 100)) ** 2
        j_ss = analytical.permeation_steady_flux(D, case.upstream_concentration, L)
        t_lag = analytical.permeation_time_lag(D, L)
        return {
            "values": {
                "permeation_flux_ss": j_ss * (1.0 + 0.2 * err),
                "time_lag": t_lag * (1.0 + err),
                "D_eff": D / (1.0 + err),
                "D": D,
            },
            "checks": {"steady_flux_balance": 1e-4},
            "profiles": {},
            "notes": ["synthetic result from the mock backend"],
        }
    if isinstance(case, TDSCase):
        import numpy as np

        T = np.linspace(case.implantation_temperature, case.final_temperature, 400)
        model = reduced.FirstOrderDesorptionModel(
            T, thickness=case.thickness, T0=case.implantation_temperature, beta=case.ramp_rate
        )
        tr = case.traps[0]
        flux = model({"E_p": tr.E_p, "log10_p_0": math.log10(tr.p_0), "n_t0": min(tr.n, 1e25)})
        i = int(np.argmax(flux))
        return {
            "values": {
                "T_peak": float(T[i]),
                "peak_flux": float(flux[i]),
                "desorbed_inventory": float(np.trapezoid(flux, (T - T[0]) / case.ramp_rate)),
            },
            "profiles": {"temperature": T.tolist(), "desorption_flux": flux.tolist()},
            "checks": {},
            "notes": ["synthetic TDS from the first-order reduced model"],
        }
    raise TypeError(f"unsupported case {type(case)}")
