"""FESTIM backend for hydrogen-isotope (tritium) transport in solids.

The agent process never imports ``festim`` itself: the case directory gets a
``params.json`` plus a copy of :mod:`run_festim` and an ``Allrun`` that
executes it with whatever Python has FESTIM (a conda env, the
``dolfinx/dolfinx`` container, or an HPC module).  Results come back as
``results.csv`` which is post-processed here with NumPy only.
"""

from __future__ import annotations

import json
import math
import shutil
from pathlib import Path
from typing import Any

import numpy as np

from nuagent import __version__
from nuagent.backends.base import (
    CaseHandle,
    ConvergenceReport,
    QoIResult,
    spec_hash,
    write_case_metadata,
)
from nuagent.physics import analytical
from nuagent.spec import PermeationCase, SimulationSpec, TDSCase

RUNNER = Path(__file__).parent / "run_festim.py"

ADJUSTABLE = {"n_steps": (10, 1_000_000), "atol": (1e-6, 1e15), "rtol": (1e-14, 1e-3)}

ALLRUN = """#!/bin/bash
# Generated by NuAgent {version} — FESTIM case '{name}'
set -o pipefail
cd "$(dirname "$0")" || exit 1
PY="${{NUAGENT_FESTIM_PYTHON:-python3}}"
echo "[nuagent] using $PY ($($PY -c 'import festim,sys;print("festim",festim.__version__)' 2>/dev/null || echo 'festim not importable'))"
"$PY" run_festim.py . > log.festim 2>&1
rc=$?
[ $rc -ne 0 ] && echo "[nuagent] FAILED ($rc): see log.festim" >&2
echo "[nuagent] done"
exit $rc
"""


class FESTIMBackend:
    name = "festim"

    def available(self) -> bool:
        try:
            import festim  # noqa: F401

            return True
        except Exception:
            return shutil.which("nuagent-festim-python") is not None

    # ------------------------------------------------------------------ #
    def _params(
        self, spec: SimulationSpec, refinement: float, adjustments: dict[str, Any] | None
    ) -> dict:
        case = spec.case
        adjustments = adjustments or {}
        for key in adjustments:
            if key not in ADJUSTABLE:
                raise ValueError(
                    f"adjustment {key!r} not allowed for FESTIM; permitted: {sorted(ADJUSTABLE)}"
                )
        if isinstance(case, PermeationCase):
            D = analytical.arrhenius(case.material.D_0, case.material.E_D, case.temperature)
            final_time = case.final_time or 6.0 * case.thickness**2 / D
            params = {
                "kind": "permeation",
                "material": case.material.model_dump(),
                "thickness": case.thickness,
                "temperature": case.temperature,
                "upstream_concentration": case.upstream_concentration,
                "traps": [t.model_dump() for t in case.traps],
                "n_cells": int(round(case.n_cells * refinement)),
                "n_steps": int(round(adjustments.get("n_steps", case.n_steps) * refinement)),
                "final_time": final_time,
                "diffusivity": D,
            }
        elif isinstance(case, TDSCase):
            params = {
                "kind": "tds",
                "material": case.material.model_dump(),
                "thickness": case.thickness,
                "traps": [t.model_dump() for t in case.traps],
                "implantation_flux": case.implantation_flux,
                "implantation_range": case.implantation_range,
                "implantation_width": case.implantation_width,
                "implantation_time": case.implantation_time,
                "implantation_temperature": case.implantation_temperature,
                "rest_time": case.rest_time,
                "ramp_rate": case.ramp_rate,
                "final_temperature": case.final_temperature,
                "n_cells": int(round(case.n_cells * refinement)),
            }
        else:
            raise TypeError("FESTIM backend supports PermeationCase and TDSCase")
        for key in ("atol", "rtol"):
            if key in adjustments:
                lo, hi = ADJUSTABLE[key]
                params[key] = min(max(adjustments[key], lo), hi)
        return params

    def build(
        self,
        spec: SimulationSpec,
        workdir: Path,
        refinement: float = 1.0,
        adjustments: dict[str, Any] | None = None,
    ) -> CaseHandle:
        workdir = Path(workdir)
        if workdir.exists():
            shutil.rmtree(workdir)
        workdir.mkdir(parents=True)
        params = self._params(spec, refinement, adjustments)
        (workdir / "params.json").write_text(json.dumps(params, indent=2))
        shutil.copy(RUNNER, workdir / "run_festim.py")
        allrun = workdir / "Allrun"
        allrun.write_text(ALLRUN.format(version=__version__, name=spec.name), newline="\n")
        allrun.chmod(0o755)
        h = spec.case.thickness / params["n_cells"]
        handle = CaseHandle(
            path=workdir,
            backend=self.name,
            spec_hash=spec_hash(spec, {"refinement": refinement, "adjustments": adjustments or {}}),
            refinement=refinement,
            representative_h=h,
            n_cells=params["n_cells"],
            metadata={"params": params, "adjustments": adjustments or {}, "log": "log.festim"},
        )
        write_case_metadata(handle, spec)
        return handle

    # ------------------------------------------------------------------ #
    def parse_log(self, case: CaseHandle) -> ConvergenceReport:
        info_path = case.path / "run_info.json"
        log_path = case.path / "log.festim"
        log = log_path.read_text(errors="replace") if log_path.exists() else ""
        if not info_path.exists():
            reason = "run_info.json missing — runner did not start"
            if "No module named" in log:
                reason = "FESTIM/dolfinx not importable in the execution environment"
            return ConvergenceReport(False, False, False, 0, reason=reason)
        info = json.loads(info_path.read_text())
        completed = info.get("status") == "completed"
        diverged = "did not converge" in log or "DIVERGED" in log.upper()
        reason = info.get("error", "") or ("FESTIM run completed" if completed else "runner failed")
        return ConvergenceReport(
            converged=completed and not diverged,
            diverged=diverged,
            completed=completed,
            iterations=int(info.get("n_steps", 0)),
            reason=reason,
        )

    def extract_qois(self, case: CaseHandle, spec: SimulationSpec) -> QoIResult:
        data = np.genfromtxt(case.path / "results.csv", delimiter=",", names=True)
        t = data["t"]
        params = case.metadata["params"]
        if params["kind"] == "permeation":
            J = np.abs(data["flux_downstream"])
            j_ss = float(np.mean(J[int(0.9 * len(J)) :]))
            # time lag: integral of (J_ss - J) dt / J_ss  (Daynes-Barrer)
            t_lag = float(np.trapezoid(j_ss - J, t) / j_ss) if j_ss > 0 else math.nan
            L = params["thickness"]
            d_eff = L**2 / (6.0 * t_lag) if t_lag > 0 else math.nan
            checks = {}
            if "flux_upstream" in data.dtype.names:
                j_up = float(np.mean(np.abs(data["flux_upstream"][int(0.9 * len(J)) :])))
                checks["steady_flux_balance"] = (j_up - j_ss) / j_ss if j_ss else math.nan
            values = {
                "permeation_flux_ss": j_ss,
                "time_lag": t_lag,
                "D_eff": d_eff,
                "D": params["diffusivity"],
                "final_time": float(t[-1]),
            }
            profiles = {"t": t.tolist(), "flux_downstream": J.tolist()}
            return QoIResult(values=values, profiles=profiles, checks=checks)
        # TDS
        flux = data["desorption_flux"]
        T = data["temperature"]
        ramp = T > T[0] + 1e-6
        i_peak = int(np.argmax(np.where(ramp, flux, -np.inf)))
        inventory = float(np.trapezoid(flux, t))
        values = {
            "T_peak": float(T[i_peak]),
            "peak_flux": float(flux[i_peak]),
            "desorbed_inventory": inventory,
        }
        profiles = {"t": t.tolist(), "temperature": T.tolist(), "desorption_flux": flux.tolist()}
        return QoIResult(values=values, profiles=profiles)
